spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_advanced_test
    password: 1007
    username: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update



server:
  port: 8085
