insert into tags (id, name) values (1, 'Public Utilities');
insert into tags (id, name) values (2, 'n/a');
insert into tags (id, name) values (3, 'Health Care');
insert into tags (id, name) values (4, 'Finance');
insert into tags (id, name) values (5, 'Consumer Durables');
insert into tags (id, name) values (6, 'Consumer Services');
insert into tags (id, name) values (7, 'Basic Industries');
insert into tags (id, name) values (8, 'n/a');
insert into tags (id, name) values (9, 'Basic Industries');
insert into tags (id, name) values (10, 'Public Utilities');
insert into tags (id, name) values (11, 'Basic Industries');
insert into tags (id, name) values (12, 'Finance');
insert into tags (id, name) values (13, 'Consumer Services');
insert into tags (id, name) values (14, 'Technology');
insert into tags (id, name) values (15, 'n/a');
insert into tags (id, name) values (16, 'Consumer Durables');
insert into tags (id, name) values (17, 'Technology');
insert into tags (id, name) values (18, 'Capital Goods');
insert into tags (id, name) values (19, 'Health Care');
insert into tags (id, name) values (20, 'Finance');
insert into tags (id, name) values (21, 'Energy');
insert into tags (id, name) values (22, 'Health Care');
insert into tags (id, name) values (23, 'n/a');
insert into tags (id, name) values (24, 'Finance');
insert into tags (id, name) values (25, 'Consumer Non-Durables');
insert into tags (id, name) values (26, 'n/a');
insert into tags (id, name) values (27, 'Miscellaneous');
insert into tags (id, name) values (28, 'n/a');
insert into tags (id, name) values (29, 'Basic Industries');
insert into tags (id, name) values (30, 'Public Utilities');
insert into tags (id, name) values (31, 'Technology');
insert into tags (id, name) values (32, 'Health Care');
insert into tags (id, name) values (33, 'Energy');
insert into tags (id, name) values (34, 'n/a');
insert into tags (id, name) values (35, 'Technology');
insert into tags (id, name) values (36, 'Technology');
insert into tags (id, name) values (37, 'n/a');
insert into tags (id, name) values (38, 'Transportation');
insert into tags (id, name) values (39, 'n/a');
insert into tags (id, name) values (40, 'Public Utilities');
insert into tags (id, name) values (41, 'Technology');
insert into tags (id, name) values (42, 'n/a');
insert into tags (id, name) values (43, 'n/a');
insert into tags (id, name) values (44, 'Consumer Durables');
insert into tags (id, name) values (45, 'n/a');
insert into tags (id, name) values (46, 'Public Utilities');
insert into tags (id, name) values (47, 'Capital Goods');
insert into tags (id, name) values (48, 'Public Utilities');
insert into tags (id, name) values (49, 'n/a');
insert into tags (id, name) values (50, 'n/a');
insert into tags (id, name) values (51, 'Consumer Services');
insert into tags (id, name) values (52, 'Consumer Services');
insert into tags (id, name) values (53, 'n/a');
insert into tags (id, name) values (54, 'n/a');
insert into tags (id, name) values (55, 'Transportation');
insert into tags (id, name) values (56, 'n/a');
insert into tags (id, name) values (57, 'Finance');
insert into tags (id, name) values (58, 'n/a');
insert into tags (id, name) values (59, 'Public Utilities');
insert into tags (id, name) values (60, 'n/a');
insert into tags (id, name) values (61, 'Consumer Services');
insert into tags (id, name) values (62, 'Miscellaneous');
insert into tags (id, name) values (63, 'Finance');
insert into tags (id, name) values (64, 'Miscellaneous');
insert into tags (id, name) values (65, 'Basic Industries');
insert into tags (id, name) values (66, 'n/a');
insert into tags (id, name) values (67, 'Technology');
insert into tags (id, name) values (68, 'Finance');
insert into tags (id, name) values (69, 'n/a');
insert into tags (id, name) values (70, 'Finance');
insert into tags (id, name) values (71, 'Miscellaneous');
insert into tags (id, name) values (72, 'Finance');
insert into tags (id, name) values (73, 'n/a');
insert into tags (id, name) values (74, 'Finance');
insert into tags (id, name) values (75, 'Consumer Services');
insert into tags (id, name) values (76, 'Basic Industries');
insert into tags (id, name) values (77, 'Capital Goods');
insert into tags (id, name) values (78, 'Technology');
insert into tags (id, name) values (79, 'n/a');
insert into tags (id, name) values (80, 'Miscellaneous');
insert into tags (id, name) values (81, 'Finance');
insert into tags (id, name) values (82, 'Finance');
insert into tags (id, name) values (83, 'Consumer Durables');
insert into tags (id, name) values (84, 'Consumer Non-Durables');
insert into tags (id, name) values (85, 'Health Care');
insert into tags (id, name) values (86, 'Technology');
insert into tags (id, name) values (87, 'Public Utilities');
insert into tags (id, name) values (88, 'n/a');
insert into tags (id, name) values (89, 'Finance');
insert into tags (id, name) values (90, 'Finance');
insert into tags (id, name) values (91, 'Consumer Services');
insert into tags (id, name) values (92, 'Technology');
insert into tags (id, name) values (93, 'Finance');
insert into tags (id, name) values (94, 'Energy');
insert into tags (id, name) values (95, 'Consumer Services');
insert into tags (id, name) values (96, 'Finance');
insert into tags (id, name) values (97, 'Finance');
insert into tags (id, name) values (98, 'Finance');
insert into tags (id, name) values (99, 'Energy');
insert into tags (id, name) values (100, 'Consumer Durables');
insert into tags (id, name) values (101, 'n/a');
insert into tags (id, name) values (102, 'Consumer Services');
insert into tags (id, name) values (103, 'Finance');
insert into tags (id, name) values (104, 'Finance');
insert into tags (id, name) values (105, 'Consumer Services');
insert into tags (id, name) values (106, 'Technology');
insert into tags (id, name) values (107, 'Energy');
insert into tags (id, name) values (108, 'n/a');
insert into tags (id, name) values (109, 'Capital Goods');
insert into tags (id, name) values (110, 'Finance');
insert into tags (id, name) values (111, 'Consumer Services');
insert into tags (id, name) values (112, 'Consumer Services');
insert into tags (id, name) values (113, 'Technology');
insert into tags (id, name) values (114, 'Technology');
insert into tags (id, name) values (115, 'Finance');
insert into tags (id, name) values (116, 'n/a');
insert into tags (id, name) values (117, 'Health Care');
insert into tags (id, name) values (118, 'n/a');
insert into tags (id, name) values (119, 'Finance');
insert into tags (id, name) values (120, 'Consumer Services');
insert into tags (id, name) values (121, 'Health Care');
insert into tags (id, name) values (122, 'Health Care');
insert into tags (id, name) values (123, 'Consumer Services');
insert into tags (id, name) values (124, 'Consumer Durables');
insert into tags (id, name) values (125, 'Finance');
insert into tags (id, name) values (126, 'Finance');
insert into tags (id, name) values (127, 'Capital Goods');
insert into tags (id, name) values (128, 'Consumer Services');
insert into tags (id, name) values (129, 'Consumer Durables');
insert into tags (id, name) values (130, 'Public Utilities');
insert into tags (id, name) values (131, 'n/a');
insert into tags (id, name) values (132, 'Finance');
insert into tags (id, name) values (133, 'Finance');
insert into tags (id, name) values (134, 'Energy');
insert into tags (id, name) values (135, 'Finance');
insert into tags (id, name) values (136, 'Public Utilities');
insert into tags (id, name) values (137, 'Finance');
insert into tags (id, name) values (138, 'Health Care');
insert into tags (id, name) values (139, 'Basic Industries');
insert into tags (id, name) values (140, 'Health Care');
insert into tags (id, name) values (141, 'Finance');
insert into tags (id, name) values (142, 'Finance');
insert into tags (id, name) values (143, 'Energy');
insert into tags (id, name) values (144, 'Capital Goods');
insert into tags (id, name) values (145, 'Miscellaneous');
insert into tags (id, name) values (146, 'Public Utilities');
insert into tags (id, name) values (147, 'n/a');
insert into tags (id, name) values (148, 'Health Care');
insert into tags (id, name) values (149, 'Consumer Services');
insert into tags (id, name) values (150, 'Technology');
insert into tags (id, name) values (151, 'Health Care');
insert into tags (id, name) values (152, 'n/a');
insert into tags (id, name) values (153, 'n/a');
insert into tags (id, name) values (154, 'Consumer Durables');
insert into tags (id, name) values (155, 'Public Utilities');
insert into tags (id, name) values (156, 'Transportation');
insert into tags (id, name) values (157, 'Consumer Durables');
insert into tags (id, name) values (158, 'n/a');
insert into tags (id, name) values (159, 'Health Care');
insert into tags (id, name) values (160, 'Energy');
insert into tags (id, name) values (161, 'n/a');
insert into tags (id, name) values (162, 'Finance');
insert into tags (id, name) values (163, 'n/a');
insert into tags (id, name) values (164, 'n/a');
insert into tags (id, name) values (165, 'Transportation');
insert into tags (id, name) values (166, 'Health Care');
insert into tags (id, name) values (167, 'Technology');
insert into tags (id, name) values (168, 'Transportation');
insert into tags (id, name) values (169, 'Consumer Services');
insert into tags (id, name) values (170, 'Consumer Non-Durables');
insert into tags (id, name) values (171, 'Technology');
insert into tags (id, name) values (172, 'Public Utilities');
insert into tags (id, name) values (173, 'n/a');
insert into tags (id, name) values (174, 'Finance');
insert into tags (id, name) values (175, 'Basic Industries');
insert into tags (id, name) values (176, 'Health Care');
insert into tags (id, name) values (177, 'n/a');
insert into tags (id, name) values (178, 'n/a');
insert into tags (id, name) values (179, 'Consumer Non-Durables');
insert into tags (id, name) values (180, 'Finance');
insert into tags (id, name) values (181, 'n/a');
insert into tags (id, name) values (182, 'Consumer Services');
insert into tags (id, name) values (183, 'n/a');
insert into tags (id, name) values (184, 'Miscellaneous');
insert into tags (id, name) values (185, 'Finance');
insert into tags (id, name) values (186, 'Health Care');
insert into tags (id, name) values (187, 'Technology');
insert into tags (id, name) values (188, 'Capital Goods');
insert into tags (id, name) values (189, 'n/a');
insert into tags (id, name) values (190, 'Consumer Services');
insert into tags (id, name) values (191, 'Transportation');
insert into tags (id, name) values (192, 'Capital Goods');
insert into tags (id, name) values (193, 'Finance');
insert into tags (id, name) values (194, 'Consumer Services');
insert into tags (id, name) values (195, 'n/a');
insert into tags (id, name) values (196, 'Consumer Services');
insert into tags (id, name) values (197, 'Finance');
insert into tags (id, name) values (198, 'Basic Industries');
insert into tags (id, name) values (199, 'Technology');
insert into tags (id, name) values (200, 'n/a');
insert into tags (id, name) values (201, 'n/a');
insert into tags (id, name) values (202, 'n/a');
insert into tags (id, name) values (203, 'Finance');
insert into tags (id, name) values (204, 'n/a');
insert into tags (id, name) values (205, 'Technology');
insert into tags (id, name) values (206, 'Finance');
insert into tags (id, name) values (207, 'Public Utilities');
insert into tags (id, name) values (208, 'Finance');
insert into tags (id, name) values (209, 'Consumer Durables');
insert into tags (id, name) values (210, 'Consumer Non-Durables');
insert into tags (id, name) values (211, 'Consumer Services');
insert into tags (id, name) values (212, 'Miscellaneous');
insert into tags (id, name) values (213, 'Finance');
insert into tags (id, name) values (214, 'Health Care');
insert into tags (id, name) values (215, 'Capital Goods');
insert into tags (id, name) values (216, 'n/a');
insert into tags (id, name) values (217, 'Health Care');
insert into tags (id, name) values (218, 'Energy');
insert into tags (id, name) values (219, 'n/a');
insert into tags (id, name) values (220, 'Basic Industries');
insert into tags (id, name) values (221, 'Public Utilities');
insert into tags (id, name) values (222, 'Health Care');
insert into tags (id, name) values (223, 'Consumer Non-Durables');
insert into tags (id, name) values (224, 'Health Care');
insert into tags (id, name) values (225, 'n/a');
insert into tags (id, name) values (226, 'Energy');
insert into tags (id, name) values (227, 'Basic Industries');
insert into tags (id, name) values (228, 'Health Care');
insert into tags (id, name) values (229, 'Consumer Non-Durables');
insert into tags (id, name) values (230, 'Finance');
insert into tags (id, name) values (231, 'Technology');
insert into tags (id, name) values (232, 'n/a');
insert into tags (id, name) values (233, 'Health Care');
insert into tags (id, name) values (234, 'Basic Industries');
insert into tags (id, name) values (235, 'Technology');
insert into tags (id, name) values (236, 'Capital Goods');
insert into tags (id, name) values (237, 'Consumer Services');
insert into tags (id, name) values (238, 'Basic Industries');
insert into tags (id, name) values (239, 'Technology');
insert into tags (id, name) values (240, 'Basic Industries');
insert into tags (id, name) values (241, 'Energy');
insert into tags (id, name) values (242, 'Energy');
insert into tags (id, name) values (243, 'Finance');
insert into tags (id, name) values (244, 'Health Care');
insert into tags (id, name) values (245, 'n/a');
insert into tags (id, name) values (246, 'Consumer Services');
insert into tags (id, name) values (247, 'Transportation');
insert into tags (id, name) values (248, 'n/a');
insert into tags (id, name) values (249, 'Finance');
insert into tags (id, name) values (250, 'n/a');
insert into tags (id, name) values (251, 'Health Care');
insert into tags (id, name) values (252, 'Finance');
insert into tags (id, name) values (253, 'Finance');
insert into tags (id, name) values (254, 'Consumer Services');
insert into tags (id, name) values (255, 'Miscellaneous');
insert into tags (id, name) values (256, 'Consumer Services');
insert into tags (id, name) values (257, 'Miscellaneous');
insert into tags (id, name) values (258, 'Health Care');
insert into tags (id, name) values (259, 'Technology');
insert into tags (id, name) values (260, 'Consumer Services');
insert into tags (id, name) values (261, 'Finance');
insert into tags (id, name) values (262, 'Consumer Services');
insert into tags (id, name) values (263, 'Miscellaneous');
insert into tags (id, name) values (264, 'Finance');
insert into tags (id, name) values (265, 'Capital Goods');
insert into tags (id, name) values (266, 'Technology');
insert into tags (id, name) values (267, 'Basic Industries');
insert into tags (id, name) values (268, 'Public Utilities');
insert into tags (id, name) values (269, 'Consumer Non-Durables');
insert into tags (id, name) values (270, 'Consumer Services');
insert into tags (id, name) values (271, 'Miscellaneous');
insert into tags (id, name) values (272, 'Consumer Services');
insert into tags (id, name) values (273, 'n/a');
insert into tags (id, name) values (274, 'Finance');
insert into tags (id, name) values (275, 'Finance');
insert into tags (id, name) values (276, 'n/a');
insert into tags (id, name) values (277, 'Finance');
insert into tags (id, name) values (278, 'Energy');
insert into tags (id, name) values (279, 'Miscellaneous');
insert into tags (id, name) values (280, 'Finance');
insert into tags (id, name) values (281, 'n/a');
insert into tags (id, name) values (282, 'Capital Goods');
insert into tags (id, name) values (283, 'n/a');
insert into tags (id, name) values (284, 'Health Care');
insert into tags (id, name) values (285, 'Technology');
insert into tags (id, name) values (286, 'n/a');
insert into tags (id, name) values (287, 'n/a');
insert into tags (id, name) values (288, 'Health Care');
insert into tags (id, name) values (289, 'n/a');
insert into tags (id, name) values (290, 'Finance');
insert into tags (id, name) values (291, 'Energy');
insert into tags (id, name) values (292, 'Finance');
insert into tags (id, name) values (293, 'n/a');
insert into tags (id, name) values (294, 'Consumer Services');
insert into tags (id, name) values (295, 'Finance');
insert into tags (id, name) values (296, 'Miscellaneous');
insert into tags (id, name) values (297, 'Finance');
insert into tags (id, name) values (298, 'Consumer Non-Durables');
insert into tags (id, name) values (299, 'Public Utilities');
insert into tags (id, name) values (300, 'Technology');
insert into tags (id, name) values (301, 'n/a');
insert into tags (id, name) values (302, 'Miscellaneous');
insert into tags (id, name) values (303, 'n/a');
insert into tags (id, name) values (304, 'Finance');
insert into tags (id, name) values (305, 'Consumer Durables');
insert into tags (id, name) values (306, 'n/a');
insert into tags (id, name) values (307, 'Public Utilities');
insert into tags (id, name) values (308, 'Technology');
insert into tags (id, name) values (309, 'Technology');
insert into tags (id, name) values (310, 'Finance');
insert into tags (id, name) values (311, 'Finance');
insert into tags (id, name) values (312, 'Capital Goods');
insert into tags (id, name) values (313, 'Public Utilities');
insert into tags (id, name) values (314, 'n/a');
insert into tags (id, name) values (315, 'n/a');
insert into tags (id, name) values (316, 'Energy');
insert into tags (id, name) values (317, 'Miscellaneous');
insert into tags (id, name) values (318, 'Consumer Services');
insert into tags (id, name) values (319, 'Finance');
insert into tags (id, name) values (320, 'Consumer Services');
insert into tags (id, name) values (321, 'n/a');
insert into tags (id, name) values (322, 'n/a');
insert into tags (id, name) values (323, 'Technology');
insert into tags (id, name) values (324, 'Consumer Services');
insert into tags (id, name) values (325, 'n/a');
insert into tags (id, name) values (326, 'Health Care');
insert into tags (id, name) values (327, 'Consumer Services');
insert into tags (id, name) values (328, 'Public Utilities');
insert into tags (id, name) values (329, 'Finance');
insert into tags (id, name) values (330, 'Consumer Services');
insert into tags (id, name) values (331, 'Capital Goods');
insert into tags (id, name) values (332, 'Finance');
insert into tags (id, name) values (333, 'n/a');
insert into tags (id, name) values (334, 'Consumer Non-Durables');
insert into tags (id, name) values (335, 'Public Utilities');
insert into tags (id, name) values (336, 'Miscellaneous');
insert into tags (id, name) values (337, 'Finance');
insert into tags (id, name) values (338, 'n/a');
insert into tags (id, name) values (339, 'n/a');
insert into tags (id, name) values (340, 'Capital Goods');
insert into tags (id, name) values (341, 'Technology');
insert into tags (id, name) values (342, 'n/a');
insert into tags (id, name) values (343, 'Basic Industries');
insert into tags (id, name) values (344, 'Technology');
insert into tags (id, name) values (345, 'Technology');
insert into tags (id, name) values (346, 'n/a');
insert into tags (id, name) values (347, 'Public Utilities');
insert into tags (id, name) values (348, 'Transportation');
insert into tags (id, name) values (349, 'Transportation');
insert into tags (id, name) values (350, 'Public Utilities');
insert into tags (id, name) values (351, 'Energy');
insert into tags (id, name) values (352, 'Consumer Services');
insert into tags (id, name) values (353, 'Basic Industries');
insert into tags (id, name) values (354, 'Energy');
insert into tags (id, name) values (355, 'Capital Goods');
insert into tags (id, name) values (356, 'Finance');
insert into tags (id, name) values (357, 'Health Care');
insert into tags (id, name) values (358, 'Technology');
insert into tags (id, name) values (359, 'Miscellaneous');
insert into tags (id, name) values (360, 'Miscellaneous');
insert into tags (id, name) values (361, 'Public Utilities');
insert into tags (id, name) values (362, 'n/a');
insert into tags (id, name) values (363, 'Consumer Services');
insert into tags (id, name) values (364, 'Finance');
insert into tags (id, name) values (365, 'Finance');
insert into tags (id, name) values (366, 'Finance');
insert into tags (id, name) values (367, 'Consumer Services');
insert into tags (id, name) values (368, 'Consumer Services');
insert into tags (id, name) values (369, 'n/a');
insert into tags (id, name) values (370, 'Consumer Services');
insert into tags (id, name) values (371, 'Finance');
insert into tags (id, name) values (372, 'Basic Industries');
insert into tags (id, name) values (373, 'Health Care');
insert into tags (id, name) values (374, 'Transportation');
insert into tags (id, name) values (375, 'Finance');
insert into tags (id, name) values (376, 'Technology');
insert into tags (id, name) values (377, 'Transportation');
insert into tags (id, name) values (378, 'Consumer Non-Durables');
insert into tags (id, name) values (379, 'n/a');
insert into tags (id, name) values (380, 'n/a');
insert into tags (id, name) values (381, 'Consumer Services');
insert into tags (id, name) values (382, 'Public Utilities');
insert into tags (id, name) values (383, 'Health Care');
insert into tags (id, name) values (384, 'n/a');
insert into tags (id, name) values (385, 'Finance');
insert into tags (id, name) values (386, 'Capital Goods');
insert into tags (id, name) values (387, 'Finance');
insert into tags (id, name) values (388, 'Consumer Services');
insert into tags (id, name) values (389, 'Consumer Non-Durables');
insert into tags (id, name) values (390, 'n/a');
insert into tags (id, name) values (391, 'Finance');
insert into tags (id, name) values (392, 'Basic Industries');
insert into tags (id, name) values (393, 'Finance');
insert into tags (id, name) values (394, 'Health Care');
insert into tags (id, name) values (395, 'Consumer Services');
insert into tags (id, name) values (396, 'Finance');
insert into tags (id, name) values (397, 'Health Care');
insert into tags (id, name) values (398, 'Miscellaneous');
insert into tags (id, name) values (399, 'Finance');
insert into tags (id, name) values (400, 'Capital Goods');
insert into tags (id, name) values (401, 'n/a');
insert into tags (id, name) values (402, 'Capital Goods');
insert into tags (id, name) values (403, 'Technology');
insert into tags (id, name) values (404, 'n/a');
insert into tags (id, name) values (405, 'n/a');
insert into tags (id, name) values (406, 'Finance');
insert into tags (id, name) values (407, 'Consumer Services');
insert into tags (id, name) values (408, 'Energy');
insert into tags (id, name) values (409, 'Technology');
insert into tags (id, name) values (410, 'Finance');
insert into tags (id, name) values (411, 'Finance');
insert into tags (id, name) values (412, 'Finance');
insert into tags (id, name) values (413, 'n/a');
insert into tags (id, name) values (414, 'Transportation');
insert into tags (id, name) values (415, 'Capital Goods');
insert into tags (id, name) values (416, 'Basic Industries');
insert into tags (id, name) values (417, 'Capital Goods');
insert into tags (id, name) values (418, 'Public Utilities');
insert into tags (id, name) values (419, 'Finance');
insert into tags (id, name) values (420, 'Consumer Services');
insert into tags (id, name) values (421, 'Health Care');
insert into tags (id, name) values (422, 'n/a');
insert into tags (id, name) values (423, 'Health Care');
insert into tags (id, name) values (424, 'Technology');
insert into tags (id, name) values (425, 'Health Care');
insert into tags (id, name) values (426, 'Consumer Durables');
insert into tags (id, name) values (427, 'Basic Industries');
insert into tags (id, name) values (428, 'Capital Goods');
insert into tags (id, name) values (429, 'n/a');
insert into tags (id, name) values (430, 'Finance');
insert into tags (id, name) values (431, 'Finance');
insert into tags (id, name) values (432, 'Finance');
insert into tags (id, name) values (433, 'Consumer Services');
insert into tags (id, name) values (434, 'Public Utilities');
insert into tags (id, name) values (435, 'n/a');
insert into tags (id, name) values (436, 'n/a');
insert into tags (id, name) values (437, 'Capital Goods');
insert into tags (id, name) values (438, 'Finance');
insert into tags (id, name) values (439, 'Consumer Services');
insert into tags (id, name) values (440, 'Miscellaneous');
insert into tags (id, name) values (441, 'Technology');
insert into tags (id, name) values (442, 'n/a');
insert into tags (id, name) values (443, 'Health Care');
insert into tags (id, name) values (444, 'Technology');
insert into tags (id, name) values (445, 'Consumer Services');
insert into tags (id, name) values (446, 'Technology');
insert into tags (id, name) values (447, 'n/a');
insert into tags (id, name) values (448, 'Consumer Services');
insert into tags (id, name) values (449, 'n/a');
insert into tags (id, name) values (450, 'Finance');
insert into tags (id, name) values (451, 'Health Care');
insert into tags (id, name) values (452, 'n/a');
insert into tags (id, name) values (453, 'Finance');
insert into tags (id, name) values (454, 'Capital Goods');
insert into tags (id, name) values (455, 'Health Care');
insert into tags (id, name) values (456, 'n/a');
insert into tags (id, name) values (457, 'Miscellaneous');
insert into tags (id, name) values (458, 'Health Care');
insert into tags (id, name) values (459, 'Technology');
insert into tags (id, name) values (460, 'Capital Goods');
insert into tags (id, name) values (461, 'Consumer Services');
insert into tags (id, name) values (462, 'n/a');
insert into tags (id, name) values (463, 'n/a');
insert into tags (id, name) values (464, 'Basic Industries');
insert into tags (id, name) values (465, 'Finance');
insert into tags (id, name) values (466, 'Capital Goods');
insert into tags (id, name) values (467, 'Basic Industries');
insert into tags (id, name) values (468, 'Basic Industries');
insert into tags (id, name) values (469, 'Health Care');
insert into tags (id, name) values (470, 'Health Care');
insert into tags (id, name) values (471, 'Technology');
insert into tags (id, name) values (472, 'Consumer Services');
insert into tags (id, name) values (473, 'Technology');
insert into tags (id, name) values (474, 'Capital Goods');
insert into tags (id, name) values (475, 'Consumer Non-Durables');
insert into tags (id, name) values (476, 'n/a');
insert into tags (id, name) values (477, 'Capital Goods');
insert into tags (id, name) values (478, 'Energy');
insert into tags (id, name) values (479, 'Finance');
insert into tags (id, name) values (480, 'Consumer Services');
insert into tags (id, name) values (481, 'Finance');
insert into tags (id, name) values (482, 'n/a');
insert into tags (id, name) values (483, 'n/a');
insert into tags (id, name) values (484, 'n/a');
insert into tags (id, name) values (485, 'n/a');
insert into tags (id, name) values (486, 'n/a');
insert into tags (id, name) values (487, 'n/a');
insert into tags (id, name) values (488, 'Energy');
insert into tags (id, name) values (489, 'Consumer Non-Durables');
insert into tags (id, name) values (490, 'n/a');
insert into tags (id, name) values (491, 'Consumer Services');
insert into tags (id, name) values (492, 'n/a');
insert into tags (id, name) values (493, 'Energy');
insert into tags (id, name) values (494, 'Finance');
insert into tags (id, name) values (495, 'Consumer Services');
insert into tags (id, name) values (496, 'Consumer Services');
insert into tags (id, name) values (497, 'Consumer Services');
insert into tags (id, name) values (498, 'Consumer Services');
insert into tags (id, name) values (499, 'Basic Industries');
insert into tags (id, name) values (500, 'Finance');
insert into tags (id, name) values (501, 'Finance');
insert into tags (id, name) values (502, 'Energy');
insert into tags (id, name) values (503, 'Technology');
insert into tags (id, name) values (504, 'Health Care');
insert into tags (id, name) values (505, 'Finance');
insert into tags (id, name) values (506, 'Health Care');
insert into tags (id, name) values (507, 'Technology');
insert into tags (id, name) values (508, 'Energy');
insert into tags (id, name) values (509, 'n/a');
insert into tags (id, name) values (510, 'n/a');
insert into tags (id, name) values (511, 'Technology');
insert into tags (id, name) values (512, 'Technology');
insert into tags (id, name) values (513, 'n/a');
insert into tags (id, name) values (514, 'Technology');
insert into tags (id, name) values (515, 'Consumer Non-Durables');
insert into tags (id, name) values (516, 'Finance');
insert into tags (id, name) values (517, 'Energy');
insert into tags (id, name) values (518, 'Energy');
insert into tags (id, name) values (519, 'Consumer Services');
insert into tags (id, name) values (520, 'Public Utilities');
insert into tags (id, name) values (521, 'Health Care');
insert into tags (id, name) values (522, 'Capital Goods');
insert into tags (id, name) values (523, 'n/a');
insert into tags (id, name) values (524, 'Technology');
insert into tags (id, name) values (525, 'n/a');
insert into tags (id, name) values (526, 'Finance');
insert into tags (id, name) values (527, 'Consumer Non-Durables');
insert into tags (id, name) values (528, 'n/a');
insert into tags (id, name) values (529, 'Finance');
insert into tags (id, name) values (530, 'n/a');
insert into tags (id, name) values (531, 'Public Utilities');
insert into tags (id, name) values (532, 'Transportation');
insert into tags (id, name) values (533, 'Finance');
insert into tags (id, name) values (534, 'Finance');
insert into tags (id, name) values (535, 'Health Care');
insert into tags (id, name) values (536, 'Health Care');
insert into tags (id, name) values (537, 'n/a');
insert into tags (id, name) values (538, 'Finance');
insert into tags (id, name) values (539, 'Health Care');
insert into tags (id, name) values (540, 'Health Care');
insert into tags (id, name) values (541, 'Finance');
insert into tags (id, name) values (542, 'n/a');
insert into tags (id, name) values (543, 'n/a');
insert into tags (id, name) values (544, 'Health Care');
insert into tags (id, name) values (545, 'Health Care');
insert into tags (id, name) values (546, 'Technology');
insert into tags (id, name) values (547, 'Finance');
insert into tags (id, name) values (548, 'n/a');
insert into tags (id, name) values (549, 'Consumer Non-Durables');
insert into tags (id, name) values (550, 'n/a');
insert into tags (id, name) values (551, 'Finance');
insert into tags (id, name) values (552, 'n/a');
insert into tags (id, name) values (553, 'Public Utilities');
insert into tags (id, name) values (554, 'Public Utilities');
insert into tags (id, name) values (555, 'Consumer Services');
insert into tags (id, name) values (556, 'Finance');
insert into tags (id, name) values (557, 'n/a');
insert into tags (id, name) values (558, 'Finance');
insert into tags (id, name) values (559, 'Finance');
insert into tags (id, name) values (560, 'Basic Industries');
insert into tags (id, name) values (561, 'Consumer Services');
insert into tags (id, name) values (562, 'Consumer Services');
insert into tags (id, name) values (563, 'Finance');
insert into tags (id, name) values (564, 'Capital Goods');
insert into tags (id, name) values (565, 'n/a');
insert into tags (id, name) values (566, 'Basic Industries');
insert into tags (id, name) values (567, 'Capital Goods');
insert into tags (id, name) values (568, 'n/a');
insert into tags (id, name) values (569, 'Capital Goods');
insert into tags (id, name) values (570, 'Transportation');
insert into tags (id, name) values (571, 'Health Care');
insert into tags (id, name) values (572, 'Consumer Services');
insert into tags (id, name) values (573, 'n/a');
insert into tags (id, name) values (574, 'Finance');
insert into tags (id, name) values (575, 'Transportation');
insert into tags (id, name) values (576, 'Consumer Non-Durables');
insert into tags (id, name) values (577, 'Energy');
insert into tags (id, name) values (578, 'Energy');
insert into tags (id, name) values (579, 'Consumer Services');
insert into tags (id, name) values (580, 'n/a');
insert into tags (id, name) values (581, 'Basic Industries');
insert into tags (id, name) values (582, 'Consumer Services');
insert into tags (id, name) values (583, 'Basic Industries');
insert into tags (id, name) values (584, 'Public Utilities');
insert into tags (id, name) values (585, 'Energy');
insert into tags (id, name) values (586, 'Technology');
insert into tags (id, name) values (587, 'Finance');
insert into tags (id, name) values (588, 'Technology');
insert into tags (id, name) values (589, 'Capital Goods');
insert into tags (id, name) values (590, 'Consumer Non-Durables');
insert into tags (id, name) values (591, 'Basic Industries');
insert into tags (id, name) values (592, 'Capital Goods');
insert into tags (id, name) values (593, 'Consumer Services');
insert into tags (id, name) values (594, 'n/a');
insert into tags (id, name) values (595, 'n/a');
insert into tags (id, name) values (596, 'Consumer Services');
insert into tags (id, name) values (597, 'Health Care');
insert into tags (id, name) values (598, 'Transportation');
insert into tags (id, name) values (599, 'Technology');
insert into tags (id, name) values (600, 'Consumer Services');
insert into tags (id, name) values (601, 'Finance');
insert into tags (id, name) values (602, 'Health Care');
insert into tags (id, name) values (603, 'Health Care');
insert into tags (id, name) values (604, 'Health Care');
insert into tags (id, name) values (605, 'Public Utilities');
insert into tags (id, name) values (606, 'Finance');
insert into tags (id, name) values (607, 'n/a');
insert into tags (id, name) values (608, 'Health Care');
insert into tags (id, name) values (609, 'n/a');
insert into tags (id, name) values (610, 'Miscellaneous');
insert into tags (id, name) values (611, 'Health Care');
insert into tags (id, name) values (612, 'n/a');
insert into tags (id, name) values (613, 'Public Utilities');
insert into tags (id, name) values (614, 'Consumer Services');
insert into tags (id, name) values (615, 'Finance');
insert into tags (id, name) values (616, 'Finance');
insert into tags (id, name) values (617, 'Public Utilities');
insert into tags (id, name) values (618, 'n/a');
insert into tags (id, name) values (619, 'Energy');
insert into tags (id, name) values (620, 'Capital Goods');
insert into tags (id, name) values (621, 'Transportation');
insert into tags (id, name) values (622, 'Consumer Durables');
insert into tags (id, name) values (623, 'Consumer Services');
insert into tags (id, name) values (624, 'Consumer Durables');
insert into tags (id, name) values (625, 'Finance');
insert into tags (id, name) values (626, 'Finance');
insert into tags (id, name) values (627, 'Health Care');
insert into tags (id, name) values (628, 'Health Care');
insert into tags (id, name) values (629, 'Finance');
insert into tags (id, name) values (630, 'Capital Goods');
insert into tags (id, name) values (631, 'Technology');
insert into tags (id, name) values (632, 'Public Utilities');
insert into tags (id, name) values (633, 'Consumer Services');
insert into tags (id, name) values (634, 'Basic Industries');
insert into tags (id, name) values (635, 'Consumer Durables');
insert into tags (id, name) values (636, 'n/a');
insert into tags (id, name) values (637, 'n/a');
insert into tags (id, name) values (638, 'Energy');
insert into tags (id, name) values (639, 'Consumer Services');
insert into tags (id, name) values (640, 'n/a');
insert into tags (id, name) values (641, 'Basic Industries');
insert into tags (id, name) values (642, 'Consumer Services');
insert into tags (id, name) values (643, 'Finance');
insert into tags (id, name) values (644, 'Consumer Services');
insert into tags (id, name) values (645, 'Public Utilities');
insert into tags (id, name) values (646, 'Basic Industries');
insert into tags (id, name) values (647, 'Basic Industries');
insert into tags (id, name) values (648, 'Finance');
insert into tags (id, name) values (649, 'Consumer Non-Durables');
insert into tags (id, name) values (650, 'Technology');
insert into tags (id, name) values (651, 'n/a');
insert into tags (id, name) values (652, 'Health Care');
insert into tags (id, name) values (653, 'Finance');
insert into tags (id, name) values (654, 'Public Utilities');
insert into tags (id, name) values (655, 'n/a');
insert into tags (id, name) values (656, 'Technology');
insert into tags (id, name) values (657, 'n/a');
insert into tags (id, name) values (658, 'Basic Industries');
insert into tags (id, name) values (659, 'Consumer Services');
insert into tags (id, name) values (660, 'Health Care');
insert into tags (id, name) values (661, 'Consumer Services');
insert into tags (id, name) values (662, 'Capital Goods');
insert into tags (id, name) values (663, 'Consumer Services');
insert into tags (id, name) values (664, 'n/a');
insert into tags (id, name) values (665, 'Health Care');
insert into tags (id, name) values (666, 'Consumer Services');
insert into tags (id, name) values (667, 'Consumer Services');
insert into tags (id, name) values (668, 'Basic Industries');
insert into tags (id, name) values (669, 'Energy');
insert into tags (id, name) values (670, 'Consumer Services');
insert into tags (id, name) values (671, 'n/a');
insert into tags (id, name) values (672, 'Finance');
insert into tags (id, name) values (673, 'Capital Goods');
insert into tags (id, name) values (674, 'Technology');
insert into tags (id, name) values (675, 'Technology');
insert into tags (id, name) values (676, 'Finance');
insert into tags (id, name) values (677, 'Health Care');
insert into tags (id, name) values (678, 'Finance');
insert into tags (id, name) values (679, 'n/a');
insert into tags (id, name) values (680, 'Health Care');
insert into tags (id, name) values (681, 'Finance');
insert into tags (id, name) values (682, 'n/a');
insert into tags (id, name) values (683, 'Public Utilities');
insert into tags (id, name) values (684, 'Capital Goods');
insert into tags (id, name) values (685, 'Energy');
insert into tags (id, name) values (686, 'Finance');
insert into tags (id, name) values (687, 'Technology');
insert into tags (id, name) values (688, 'Technology');
insert into tags (id, name) values (689, 'Health Care');
insert into tags (id, name) values (690, 'Health Care');
insert into tags (id, name) values (691, 'n/a');
insert into tags (id, name) values (692, 'n/a');
insert into tags (id, name) values (693, 'Finance');
insert into tags (id, name) values (694, 'Consumer Services');
insert into tags (id, name) values (695, 'Consumer Non-Durables');
insert into tags (id, name) values (696, 'Finance');
insert into tags (id, name) values (697, 'Consumer Services');
insert into tags (id, name) values (698, 'n/a');
insert into tags (id, name) values (699, 'Health Care');
insert into tags (id, name) values (700, 'n/a');
insert into tags (id, name) values (701, 'Finance');
insert into tags (id, name) values (702, 'Technology');
insert into tags (id, name) values (703, 'n/a');
insert into tags (id, name) values (704, 'Consumer Durables');
insert into tags (id, name) values (705, 'Finance');
insert into tags (id, name) values (706, 'Health Care');
insert into tags (id, name) values (707, 'Finance');
insert into tags (id, name) values (708, 'Capital Goods');
insert into tags (id, name) values (709, 'Energy');
insert into tags (id, name) values (710, 'Finance');
insert into tags (id, name) values (711, 'Consumer Services');
insert into tags (id, name) values (712, 'Finance');
insert into tags (id, name) values (713, 'Finance');
insert into tags (id, name) values (714, 'Consumer Services');
insert into tags (id, name) values (715, 'Finance');
insert into tags (id, name) values (716, 'Energy');
insert into tags (id, name) values (717, 'Health Care');
insert into tags (id, name) values (718, 'Basic Industries');
insert into tags (id, name) values (719, 'Technology');
insert into tags (id, name) values (720, 'Technology');
insert into tags (id, name) values (721, 'Basic Industries');
insert into tags (id, name) values (722, 'Finance');
insert into tags (id, name) values (723, 'Public Utilities');
insert into tags (id, name) values (724, 'Technology');
insert into tags (id, name) values (725, 'Health Care');
insert into tags (id, name) values (726, 'Technology');
insert into tags (id, name) values (727, 'Finance');
insert into tags (id, name) values (728, 'Consumer Services');
insert into tags (id, name) values (729, 'Finance');
insert into tags (id, name) values (730, 'Miscellaneous');
insert into tags (id, name) values (731, 'Public Utilities');
insert into tags (id, name) values (732, 'Finance');
insert into tags (id, name) values (733, 'Basic Industries');
insert into tags (id, name) values (734, 'Finance');
insert into tags (id, name) values (735, 'Technology');
insert into tags (id, name) values (736, 'n/a');
insert into tags (id, name) values (737, 'Consumer Services');
insert into tags (id, name) values (738, 'Health Care');
insert into tags (id, name) values (739, 'Finance');
insert into tags (id, name) values (740, 'Consumer Services');
insert into tags (id, name) values (741, 'n/a');
insert into tags (id, name) values (742, 'Transportation');
insert into tags (id, name) values (743, 'Capital Goods');
insert into tags (id, name) values (744, 'Technology');
insert into tags (id, name) values (745, 'Finance');
insert into tags (id, name) values (746, 'Public Utilities');
insert into tags (id, name) values (747, 'Energy');
insert into tags (id, name) values (748, 'Finance');
insert into tags (id, name) values (749, 'Consumer Services');
insert into tags (id, name) values (750, 'Health Care');
insert into tags (id, name) values (751, 'Miscellaneous');
insert into tags (id, name) values (752, 'Consumer Services');
insert into tags (id, name) values (753, 'n/a');
insert into tags (id, name) values (754, 'n/a');
insert into tags (id, name) values (755, 'Miscellaneous');
insert into tags (id, name) values (756, 'n/a');
insert into tags (id, name) values (757, 'Health Care');
insert into tags (id, name) values (758, 'Finance');
insert into tags (id, name) values (759, 'Consumer Services');
insert into tags (id, name) values (760, 'Public Utilities');
insert into tags (id, name) values (761, 'Basic Industries');
insert into tags (id, name) values (762, 'Basic Industries');
insert into tags (id, name) values (763, 'n/a');
insert into tags (id, name) values (764, 'n/a');
insert into tags (id, name) values (765, 'Finance');
insert into tags (id, name) values (766, 'Transportation');
insert into tags (id, name) values (767, 'n/a');
insert into tags (id, name) values (768, 'Consumer Services');
insert into tags (id, name) values (769, 'Finance');
insert into tags (id, name) values (770, 'Health Care');
insert into tags (id, name) values (771, 'Health Care');
insert into tags (id, name) values (772, 'Consumer Non-Durables');
insert into tags (id, name) values (773, 'Health Care');
insert into tags (id, name) values (774, 'Finance');
insert into tags (id, name) values (775, 'Transportation');
insert into tags (id, name) values (776, 'Public Utilities');
insert into tags (id, name) values (777, 'Consumer Non-Durables');
insert into tags (id, name) values (778, 'Consumer Services');
insert into tags (id, name) values (779, 'Public Utilities');
insert into tags (id, name) values (780, 'n/a');
insert into tags (id, name) values (781, 'Consumer Services');
insert into tags (id, name) values (782, 'Consumer Non-Durables');
insert into tags (id, name) values (783, 'Finance');
insert into tags (id, name) values (784, 'Finance');
insert into tags (id, name) values (785, 'Consumer Services');
insert into tags (id, name) values (786, 'n/a');
insert into tags (id, name) values (787, 'n/a');
insert into tags (id, name) values (788, 'Energy');
insert into tags (id, name) values (789, 'Basic Industries');
insert into tags (id, name) values (790, 'Consumer Services');
insert into tags (id, name) values (791, 'Consumer Durables');
insert into tags (id, name) values (792, 'Miscellaneous');
insert into tags (id, name) values (793, 'Capital Goods');
insert into tags (id, name) values (794, 'Energy');
insert into tags (id, name) values (795, 'Technology');
insert into tags (id, name) values (796, 'n/a');
insert into tags (id, name) values (797, 'n/a');
insert into tags (id, name) values (798, 'n/a');
insert into tags (id, name) values (799, 'Consumer Services');
insert into tags (id, name) values (800, 'Finance');
insert into tags (id, name) values (801, 'Public Utilities');
insert into tags (id, name) values (802, 'Capital Goods');
insert into tags (id, name) values (803, 'n/a');
insert into tags (id, name) values (804, 'n/a');
insert into tags (id, name) values (805, 'Consumer Services');
insert into tags (id, name) values (806, 'Technology');
insert into tags (id, name) values (807, 'Basic Industries');
insert into tags (id, name) values (808, 'n/a');
insert into tags (id, name) values (809, 'Miscellaneous');
insert into tags (id, name) values (810, 'Consumer Non-Durables');
insert into tags (id, name) values (811, 'n/a');
insert into tags (id, name) values (812, 'n/a');
insert into tags (id, name) values (813, 'n/a');
insert into tags (id, name) values (814, 'Finance');
insert into tags (id, name) values (815, 'Transportation');
insert into tags (id, name) values (816, 'Consumer Services');
insert into tags (id, name) values (817, 'Capital Goods');
insert into tags (id, name) values (818, 'Finance');
insert into tags (id, name) values (819, 'Finance');
insert into tags (id, name) values (820, 'Technology');
insert into tags (id, name) values (821, 'n/a');
insert into tags (id, name) values (822, 'Capital Goods');
insert into tags (id, name) values (823, 'Consumer Services');
insert into tags (id, name) values (824, 'Health Care');
insert into tags (id, name) values (825, 'n/a');
insert into tags (id, name) values (826, 'n/a');
insert into tags (id, name) values (827, 'Finance');
insert into tags (id, name) values (828, 'n/a');
insert into tags (id, name) values (829, 'Consumer Non-Durables');
insert into tags (id, name) values (830, 'Transportation');
insert into tags (id, name) values (831, 'Health Care');
insert into tags (id, name) values (832, 'Finance');
insert into tags (id, name) values (833, 'n/a');
insert into tags (id, name) values (834, 'Finance');
insert into tags (id, name) values (835, 'Basic Industries');
insert into tags (id, name) values (836, 'Technology');
insert into tags (id, name) values (837, 'Consumer Services');
insert into tags (id, name) values (838, 'n/a');
insert into tags (id, name) values (839, 'Consumer Services');
insert into tags (id, name) values (840, 'Health Care');
insert into tags (id, name) values (841, 'Consumer Services');
insert into tags (id, name) values (842, 'Consumer Services');
insert into tags (id, name) values (843, 'n/a');
insert into tags (id, name) values (844, 'Finance');
insert into tags (id, name) values (845, 'Transportation');
insert into tags (id, name) values (846, 'n/a');
insert into tags (id, name) values (847, 'Finance');
insert into tags (id, name) values (848, 'Miscellaneous');
insert into tags (id, name) values (849, 'Technology');
insert into tags (id, name) values (850, 'Technology');
insert into tags (id, name) values (851, 'Health Care');
insert into tags (id, name) values (852, 'Finance');
insert into tags (id, name) values (853, 'Basic Industries');
insert into tags (id, name) values (854, 'Consumer Services');
insert into tags (id, name) values (855, 'Miscellaneous');
insert into tags (id, name) values (856, 'Finance');
insert into tags (id, name) values (857, 'Finance');
insert into tags (id, name) values (858, 'Basic Industries');
insert into tags (id, name) values (859, 'Capital Goods');
insert into tags (id, name) values (860, 'Consumer Services');
insert into tags (id, name) values (861, 'Energy');
insert into tags (id, name) values (862, 'Consumer Services');
insert into tags (id, name) values (863, 'Health Care');
insert into tags (id, name) values (864, 'Capital Goods');
insert into tags (id, name) values (865, 'Public Utilities');
insert into tags (id, name) values (866, 'Finance');
insert into tags (id, name) values (867, 'Technology');
insert into tags (id, name) values (868, 'n/a');
insert into tags (id, name) values (869, 'Health Care');
insert into tags (id, name) values (870, 'Energy');
insert into tags (id, name) values (871, 'n/a');
insert into tags (id, name) values (872, 'n/a');
insert into tags (id, name) values (873, 'Finance');
insert into tags (id, name) values (874, 'n/a');
insert into tags (id, name) values (875, 'Miscellaneous');
insert into tags (id, name) values (876, 'Basic Industries');
insert into tags (id, name) values (877, 'Capital Goods');
insert into tags (id, name) values (878, 'Public Utilities');
insert into tags (id, name) values (879, 'Consumer Services');
insert into tags (id, name) values (880, 'Consumer Services');
insert into tags (id, name) values (881, 'Basic Industries');
insert into tags (id, name) values (882, 'Technology');
insert into tags (id, name) values (883, 'n/a');
insert into tags (id, name) values (884, 'n/a');
insert into tags (id, name) values (885, 'n/a');
insert into tags (id, name) values (886, 'Technology');
insert into tags (id, name) values (887, 'Consumer Services');
insert into tags (id, name) values (888, 'n/a');
insert into tags (id, name) values (889, 'n/a');
insert into tags (id, name) values (890, 'Health Care');
insert into tags (id, name) values (891, 'Consumer Services');
insert into tags (id, name) values (892, 'Finance');
insert into tags (id, name) values (893, 'Miscellaneous');
insert into tags (id, name) values (894, 'n/a');
insert into tags (id, name) values (895, 'Health Care');
insert into tags (id, name) values (896, 'Health Care');
insert into tags (id, name) values (897, 'n/a');
insert into tags (id, name) values (898, 'Finance');
insert into tags (id, name) values (899, 'Consumer Non-Durables');
insert into tags (id, name) values (900, 'Basic Industries');
insert into tags (id, name) values (901, 'Consumer Services');
insert into tags (id, name) values (902, 'Consumer Non-Durables');
insert into tags (id, name) values (903, 'Technology');
insert into tags (id, name) values (904, 'n/a');
insert into tags (id, name) values (905, 'n/a');
insert into tags (id, name) values (906, 'Health Care');
insert into tags (id, name) values (907, 'Consumer Services');
insert into tags (id, name) values (908, 'n/a');
insert into tags (id, name) values (909, 'Consumer Durables');
insert into tags (id, name) values (910, 'Energy');
insert into tags (id, name) values (911, 'Energy');
insert into tags (id, name) values (912, 'Consumer Services');
insert into tags (id, name) values (913, 'Finance');
insert into tags (id, name) values (914, 'Finance');
insert into tags (id, name) values (915, 'Health Care');
insert into tags (id, name) values (916, 'n/a');
insert into tags (id, name) values (917, 'Finance');
insert into tags (id, name) values (918, 'Finance');
insert into tags (id, name) values (919, 'Basic Industries');
insert into tags (id, name) values (920, 'n/a');
insert into tags (id, name) values (921, 'Energy');
insert into tags (id, name) values (922, 'Health Care');
insert into tags (id, name) values (923, 'Technology');
insert into tags (id, name) values (924, 'Health Care');
insert into tags (id, name) values (925, 'Health Care');
insert into tags (id, name) values (926, 'Technology');
insert into tags (id, name) values (927, 'Consumer Non-Durables');
insert into tags (id, name) values (928, 'Health Care');
insert into tags (id, name) values (929, 'n/a');
insert into tags (id, name) values (930, 'Consumer Durables');
insert into tags (id, name) values (931, 'Consumer Services');
insert into tags (id, name) values (932, 'Consumer Services');
insert into tags (id, name) values (933, 'Health Care');
insert into tags (id, name) values (934, 'Energy');
insert into tags (id, name) values (935, 'Consumer Services');
insert into tags (id, name) values (936, 'n/a');
insert into tags (id, name) values (937, 'Finance');
insert into tags (id, name) values (938, 'Public Utilities');
insert into tags (id, name) values (939, 'Technology');
insert into tags (id, name) values (940, 'Basic Industries');
insert into tags (id, name) values (941, 'n/a');
insert into tags (id, name) values (942, 'n/a');
insert into tags (id, name) values (943, 'Consumer Services');
insert into tags (id, name) values (944, 'Finance');
insert into tags (id, name) values (945, 'Finance');
insert into tags (id, name) values (946, 'Consumer Services');
insert into tags (id, name) values (947, 'Basic Industries');
insert into tags (id, name) values (948, 'n/a');
insert into tags (id, name) values (949, 'Health Care');
insert into tags (id, name) values (950, 'Consumer Non-Durables');
insert into tags (id, name) values (951, 'Public Utilities');
insert into tags (id, name) values (952, 'Public Utilities');
insert into tags (id, name) values (953, 'Public Utilities');
insert into tags (id, name) values (954, 'n/a');
insert into tags (id, name) values (955, 'Health Care');
insert into tags (id, name) values (956, 'Health Care');
insert into tags (id, name) values (957, 'n/a');
insert into tags (id, name) values (958, 'n/a');
insert into tags (id, name) values (959, 'Finance');
insert into tags (id, name) values (960, 'Consumer Services');
insert into tags (id, name) values (961, 'n/a');
insert into tags (id, name) values (962, 'Consumer Non-Durables');
insert into tags (id, name) values (963, 'Public Utilities');
insert into tags (id, name) values (964, 'Health Care');
insert into tags (id, name) values (965, 'Consumer Services');
insert into tags (id, name) values (966, 'Technology');
insert into tags (id, name) values (967, 'Consumer Non-Durables');
insert into tags (id, name) values (968, 'Consumer Services');
insert into tags (id, name) values (969, 'Consumer Services');
insert into tags (id, name) values (970, 'Consumer Non-Durables');
insert into tags (id, name) values (971, 'Finance');
insert into tags (id, name) values (972, 'Health Care');
insert into tags (id, name) values (973, 'Transportation');
insert into tags (id, name) values (974, 'Health Care');
insert into tags (id, name) values (975, 'Consumer Non-Durables');
insert into tags (id, name) values (976, 'Technology');
insert into tags (id, name) values (977, 'Finance');
insert into tags (id, name) values (978, 'Miscellaneous');
insert into tags (id, name) values (979, 'Consumer Services');
insert into tags (id, name) values (980, 'Finance');
insert into tags (id, name) values (981, 'Capital Goods');
insert into tags (id, name) values (982, 'Finance');
insert into tags (id, name) values (983, 'Technology');
insert into tags (id, name) values (984, 'Capital Goods');
insert into tags (id, name) values (985, 'Technology');
insert into tags (id, name) values (986, 'n/a');
insert into tags (id, name) values (987, 'Consumer Services');
insert into tags (id, name) values (988, 'n/a');
insert into tags (id, name) values (989, 'Consumer Non-Durables');
insert into tags (id, name) values (990, 'Consumer Services');
insert into tags (id, name) values (991, 'Finance');
insert into tags (id, name) values (992, 'Consumer Services');
insert into tags (id, name) values (993, 'n/a');
insert into tags (id, name) values (994, 'Energy');
insert into tags (id, name) values (995, 'Capital Goods');
insert into tags (id, name) values (996, 'Health Care');
insert into tags (id, name) values (997, 'Health Care');
insert into tags (id, name) values (998, 'Capital Goods');
insert into tags (id, name) values (999, 'Technology');
insert into tags (id, name) values (1000, 'n/a');
