spring:
  datasource:
    hikari:
      maximum-pool-size: 5
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: 1007
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8080